//this is function which take responce and process and data 
export const catfields=[{"name":"Fruit","amount":0},{"name":"Groceries","amount":0},{"name":"Electronics","amount":0},
  {"name":"Clothing","amount":0},{"name":"Travel","amount":0},{"name":"Entertainment","amount":0},
  {"name":"Bills","amount":0},{"name":"Health","amount":0},
    {"name":"Education","amount":0},{"name":"Home","amount":0},
    {"name":"sports","amount":0},{"name":"TechnologySubscriptions","amount":0},
    {"name":"pets","amount":0},{"name":"Vehicles","amount":0},{"name":"office","amount":0},
    {"name":"Beauty","amount":0},{"name":"Gifts","amount":0},{"name":"Charity","amount":0},
    {"name":"Investments","amount":0},{"name":"Taxes","amount":0},{"name":"Miscellaneous","amount":0},
    {"name":"Food","amount":0},{"name":"Other","amount":0},{"name":"Sports","amount":0}];
export const category = {
  "Fruit": [
    "apple", "banana", "orange", "mango", "grape", "pineapple", "watermelon", "kiwi", "papaya", "strawberry",
    "blueberry", "pomegranate", "lychee", "cherry", "peach", "pear", "plum", "apricot", "fig", "guava",
    "melon", "cantaloupe", "nectarine", "blackberry", "raspberry", "passionfruit", "dragonfruit", "jackfruit",
    "tangerine", "coconut", "date", "grapefruit", "kumquat", "persimmon", "quince", "cranberry", "mulberry",
    "elderberry", "gooseberry", "longan", "soursop", "starfruit", "pomelo", "breadfruit", "durian", "currant",
    "olive", "lime", "lemon", "litchi","ackee", "acerola", "ambarella", "araza", "atemoya", "babaco", "bael", "barbadine", "bilimbi", "bignay",
    "biriba", "black sapote", "buddha’s hand", "calamansi", "camu camu", "canistel", "cempedak", "chayote", "cloudberry", "cupuacu",
    "desert lime", "feijoa", "finger lime", "gac fruit", "genip", "giant granadilla", "hog plum", "horned melon", "imbe", "jabuticaba",
    "jambul", "jocote", "jujube", "kaffir lime", "kepel", "ketembilla", "langsat", "lemon aspen", "lucuma", "madrono",
    "mammee apple", "mamoncillo", "mandarin", "mangosteen", "marang", "marula", "medlar", "miracle fruit", "monstera deliciosa", "mountain papaya",
    "naranjilla", "nonu", "noni", "pitanga", "pitaya", "pulasan", "purple mangosteen", "rambutan", "rollinia", "rose apple",
    "salak", "santol", "sapodilla", "sapote", "sea buckthorn", "serviceberry", "soursop apple", "spanish lime", "sugar apple", "surinam cherry",
    "tamarillo", "tamarind", "tangelo", "tayberry", "thorn apple", "ugli fruit", "velvet apple", "voavanga", "white currant", "white sapote",
    "wild orange", "wood apple", "yunnan hackberry fruit", "ziziphus fruit", "chokeberry", "indian fig", "desert date", "brazil nut fruit", "illawarra plum", "muntingia",
    "nipa palm fruit", "pequi", "pitomba", "safou", "salmonberry", "sandoricum", "santol plum", "soncoya", "tropical almond", "water apple"

  ],
  "Groceries": [ 
    "rice", "wheat", "flour", "sugar", "salt", "milk", "bread", "butter", "cheese", "oil",
    "eggs", "yogurt", "honey", "pasta", "noodles", "cereal", "corn", "beans", "lentils", "dal",
    "spices", "pepper", "turmeric", "ginger", "garlic", "onion", "tomato", "potato", "carrot",
    "cabbage", "spinach", "lettuce", "cucumber", "capsicum", "chili", "vinegar", "soy sauce",
    "mayonnaise", "ketchup", "jam", "peanut butter", "tea", "coffee", "biscuits", "snacks",
    "chocolate", "soup", "cream", "paneer", "baking powder", "yeast","mustard", "sesame seeds", "poppy seeds", "sunflower seeds", "pumpkin seeds", "chia seeds", "flax seeds", "cashews", "almonds", "walnuts",
    "pistachios", "raisins", "dates", "figs", "apricots", "dried cranberries", "dried blueberries", "sago", "semolina", "oats",
    "barley", "millet", "quinoa", "couscous", "rye", "buckwheat", "cornmeal", "brown rice", "basmati rice", "jasmine rice",
    "olive oil", "mustard oil", "coconut oil", "ghee", "clarified butter", "vine leaves", "pickles", "mango pickle", "lime pickle", "achar",
    "tamarind paste", "curry leaves", "coriander seeds", "cumin seeds", "fennel seeds", "cardamom", "cloves", "cinnamon", "nutmeg", "mace",
    "bay leaf", "star anise", "asafoetida", "saffron", "dry ginger powder", "garam masala", "curry powder", "chili flakes", "oregano", "thyme",
    "rosemary", "basil", "parsley", "dill", "mint leaves", "dry fenugreek leaves", "black salt", "rock salt", "sea salt", "brown sugar",
    "jaggery", "molasses", "corn flour", "rice flour", "gram flour", "tapioca flour", "baking soda", "custard powder", "corn starch", "gelatin",
    "vinegar powder", "soy chunks", "tofu", "tempeh", "seitan", "vermicelli", "spring roll sheets", "bread crumbs", "instant mix", "pancake mix",
    "waffle mix", "popcorn", "nachos", "crackers", "rice cakes", "energy bars", "protein powder", "instant soup mix", "instant coffee", "green tea",
    "herbal tea", "black tea", "condensed milk", "evaporated milk", "milk powder", "milk cream", "whipped cream", "coconut milk", "almond milk", "soy milk"

  ],
  "Electronics": ["buds","Earbuds","Samsung Galaxy M15","Screen Protector","Noise Buds Z2 Wireless Earbuds",
    "laptop", "desktop", "phone", "tablet", "smartwatch", "earbuds", "headphones", "camera",
    "printer", "monitor", "keyboard", "mouse", "charger", "powerbank", "speaker", "tv", "projector",
    "router", "modem", "hard drive", "ssd", "usb", "hdmi", "adapter", "microphone", "webcam",
    "flash drive", "drone", "game console", "joystick", "graphics card", "motherboard", "ram",
    "processor", "cooler", "fan", "scanner", "stylus", "projector screen", "tripod", "gimbal",
    "headset", "smart bulb", "switch", "router cable", "keyboard cover", "tablet cover", "laptop bag", "screen protector", "hdmi cable", "usb cable",
    "bluetooth speaker", "soundbar", "subwoofer", "home theater", "dvd player", "blu-ray player", "set-top box", "smart remote", "universal remote", "streaming stick",
    "vr headset", "ar glasses", "smart glasses", "fitness tracker", "smart ring", "smart scale", "digital photo frame", "e-reader", "voice assistant", "smart hub",
    "washing machine", "dryer", "refrigerator", "microwave", "oven", "induction cooktop", "dishwasher", "air conditioner", "air purifier", "water purifier",
    "coffee maker", "electric kettle", "toaster", "blender", "mixer", "juicer", "food processor", "rice cooker", "slow cooker", "electric grill",
    "vacuum cleaner", "robot vacuum", "steam mop", "hair dryer", "hair straightener", "hair curler", "trimmer", "shaver", "electric toothbrush", "massager",
    "power strip", "extension cord", "voltage stabilizer", "ups", "inverter", "solar panel", "solar charger", "cctv camera", "security system", "doorbell camera",
    "3d printer", "thermal printer", "label printer", "photo printer", "plotter", "laminator", "barcode scanner", "rfid reader", "smart lock", "smart plug",
    "led light", "tube light", "ring light", "studio light", "flash gun", "light meter", "surge protector", "battery charger", "coin cell battery", "rechargeable battery",
    "ethernet switch", "network hub", "patch panel", "wifi extender", "mesh wifi system", "nas storage", "server", "mini pc", "raspberry pi", "arduino",
    "oscilloscope", "multimeter", "soldering iron", "power supply unit", "circuit tester", "heat gun", "project box", "breadboard", "relay module", "sensor kit"

  ],
  "Clothing": [
    "shirt", "tshirt", "jeans", "trousers", "jacket", "coat", "sweater", "hoodie", "skirt", "dress",
    "shorts", "socks", "shoes", "sandals", "boots", "cap", "hat", "scarf", "gloves", "belt",
    "tie", "suit", "blazer", "pajamas", "lingerie", "swimsuit", "tracksuit", "leggings", "cardigan",
    "vest", "blouse", "kurta", "salwar", "saree", "dupatta", "shawl", "polo shirt", "tank top",
    "sneakers", "flip flops", "slippers", "watch", "bracelet", "necklace", "earrings", "ring", "anklet", "hairband", "capri", "raincoat",
    "overcoat", "windbreaker", "poncho", "parka", "waistcoat", "overalls", "jumpsuit", "romper", "bodysuit", "crop top",
    "tube top", "halter top", "camisole", "tunic", "peacoat", "trench coat", "bomber jacket", "leather jacket", "denim jacket", "puffer jacket",
    "anorak", "kaftan", "kimono", "sarong", "lehenga", "ghagra", "churidar", "palazzo pants", "harem pants", "dhoti",
    "lungi", "poncho shawl", "cape", "shrug", "stole", "bolero jacket", "wrap dress", "maxi dress", "gown", "cocktail dress",
    "evening dress", "ball gown", "jumpskirt", "skater dress", "slip dress", "sun dress", "tulle skirt", "pleated skirt", "pencil skirt", "wrap skirt",
    "cargo pants", "chinos", "corduroy pants", "joggers", "sweatpants", "thermal wear", "long johns", "undershirt", "sports bra", "bralette",
    "camouflage jacket", "graphic tee", "henley shirt", "button-down shirt", "dress shirt", "oxford shirt", "turtleneck", "mock neck", "long sleeve tee", "three-quarter sleeve shirt",
    "beanie", "fedora", "beret", "sunhat", "cowboy hat", "turban", "bandana", "visor", "headscarf", "balaclava",
    "cummerbund", "suspenders", "glove liners", "mittens", "stockings", "tights", "fishnet stockings", "thermal socks", "knee-high socks", "ankle socks",
    "loafers", "oxfords", "derby shoes", "brogues", "heels", "wedges", "platform shoes", "clogs", "moccasins", "espadrilles"

  ],
  "Travel": ["Ola Mini",
    "bus", "train", "flight", "cab", "taxi", "uber", "ola", "metro", "ticket", "hotel",
    "hostel", "resort", "cruise", "ferry", "car rental", "bike rental", "luggage", "passport",
    "visa", "insurance", "tour guide", "map", "backpack", "suitcase", "tent", "sleeping bag",
    "camping mat", "snacks", "water bottle", "sunglasses", "camera", "tripod", "binoculars",
    "compass", "hat", "sunblock", "jacket", "hiking boots", "flip flops", "swimwear", "towel",
    "charger", "powerbank", "adapter", "raincoat", "first aid kit", "ticket app", "guidebook", "itinerary", "souvenir", "headlamp",
    "duffel bag", "daypack", "travel pillow", "blanket", "eye mask", "earplugs", "sleeping mask", "toiletry bag", "hand sanitizer", "wet wipes",
    "travel documents", "boarding pass", "rail pass", "travel wallet", "currency card", "cash pouch", "locker", "lock", "keychain", "lanyard",
    "walking stick", "trekking poles", "climbing gear", "helmet", "life jacket", "kayak", "canoe", "surfboard", "paddle board", "snorkel gear",
    "scuba gear", "diving fins", "goggles", "ski boots", "snowboard", "skis", "ice axe", "crampons", "rope", "harness",
    "travel stove", "camping lantern", "campfire grill", "portable fan", "portable heater", "mosquito net", "bug spray", "sleep sack", "camping chair", "camping table",
    "thermos", "canteen", "travel mug", "collapsible bottle", "picnic basket", "food container", "utensil set", "spork", "pocket knife", "multi-tool",
    "satellite phone", "walkie talkie", "gps device", "altimeter", "barometer", "travel adapter", "sim card", "roaming pack", "wifi hotspot", "e-sim",
    "notebook", "pen", "journal", "travel diary", "sketchbook", "postcards", "stamps", "brochure", "pamphlet", "travel magazine",
    "travel insurance papers", "medical kit", "bandages", "antiseptic cream", "painkillers", "motion sickness tablets", "allergy tablets", "water filter", "water purifier", "iodine tablets",
    "folding bike", "electric scooter", "segway", "roller skates", "skateboard", "caravan", "motorhome", "campervan", "yacht", "sailboat"
],
"Food": ["Paneer Butter Masala","Garlic Naan","Chicken Biryani","Butter Chicken","Veg Pulao","Chole Bhature",
    "restaurant", "cafe", "bakery", "fast food", "dessert", "snack", "meal", "breakfast", "lunch", "dinner",
    "burger", "cheeseburger", "veggie burger", "pizza", "margherita pizza", "pepperoni pizza", "pasta", "spaghetti", "penne", "lasagna",
    "sandwich", "sub", "wrap", "burrito", "taco", "quesadilla", "noodles", "ramen", "udon", "dumplings",
    "soup", "tomato soup", "chicken soup", "curry", "chicken curry", "paneer curry", "steak", "grilled chicken", "barbecue", "roast",
    "fish", "seafood", "prawns", "shrimp", "lobster", "crab", "oyster", "rice dish", "fried rice", "biryani",
    "omelette", "boiled egg", "scrambled egg", "pancake", "waffle", "toast", "croissant", "bagel", "muffin", "donut",
    "cookie", "brownie", "cake", "cupcake", "pie", "tart", "pudding", "ice cream", "gelato", "sorbet",
    "samosa", "pakora", "spring roll", "kebab", "shawarma", "hotdog", "sausage", "meatball", "chili", "paella",
    "salad", "fruit salad", "green salad", "coleslaw", "soup bowl", "fondue", "risotto", "quiche", "stir fry", "gratin",
    "sandesh", "gulab jamun", "jalebi", "rasgulla", "barfi", "laddu", "halwa", "kheer", "payasam", "modak",
    "smoothie", "milkshake", "energy bar", "protein bar", "granola", "oats", "porridge", "idli", "dosa", "uttapam",
    "bruschetta", "nachos", "chips", "popcorn", "pretzel", "crackers", "cheese platter", "butter chicken", "paneer tikka", "veg cutlet"
  ],
  "Entertainment": [
    "movie", "concert", "theater", "netflix", "game", "subscription", "music", "album", "ticket",
    "festival", "party", "karaoke", "board game", "puzzle", "video game", "console", "streaming",
    "tv show", "dvd", "blu-ray", "comic", "novel", "magazine", "newspaper", "painting", "sculpture",
    "museum", "exhibition", "park", "ride", "club", "bar", "pub", "arcade", "pool", "bowling",
    "dance class", "singing class", "yoga class", "gym", "sports ticket", "match", "concert ticket",
    "festival ticket", "photography", "instrument", "painting kit", "craft kit", "model kit", "lego", "card game",
    "circus", "stand-up comedy", "improv show", "opera", "ballet", "musical", "open mic", "poetry slam", "talent show", "street performance",
    "talent competition", "magic show", "illusion show", "escape room", "theme park", "water park", "zoo", "aquarium", "planetarium", "science center",
    "parade", "carnival", "cultural fair", "heritage walk", "food festival", "wine tasting", "beer festival", "live band", "dj night", "club night",
    "lan party", "cosplay event", "comic con", "gaming tournament", "e-sports", "live stream", "podcast", "audiobook", "radio show", "music video",
    "short film", "web series", "indie film", "animation", "documentary", "biopic", "musical album", "vinyl record", "cassette tape", "jukebox",
    "talent hunt", "fashion show", "art gallery", "photo exhibition", "digital art", "graffiti", "street art", "art workshop", "dance battle", "rap battle",
    "singing competition", "dj battle", "instrumental jam", "open-air cinema", "drive-in theater", "laser show", "fireworks", "light show", "sound show", "drone show",
    "treasure hunt", "scavenger hunt", "quiz night", "trivia night", "charades", "improv games", "tabletop rpg", "mini golf", "go-karting", "paintball",
    "airsoft", "laser tag", "trampoline park", "bungee jump", "skydiving video", "indoor climbing", "escape puzzle", "murder mystery dinner", "karaoke night", "virtual reality game"
]
,
  "Bills": [
    "electricity", "water", "internet", "gas", "phone", "rent", "maintenance", "insurance",
    "loan", "tax", "subscription", "cable", "tv", "parking", "garbage", "sewage", "heating",
    "cooling", "security", "property tax", "school fee", "college fee", "library fee", "parking fee",
    "club fee", "membership", "license", "permit", "fines", "penalty", "service charge", "delivery fee",
    "utility", "cleaning", "gardening", "pet fee", "gym membership", "streaming service", "app subscription",
    "software license", "cloud service", "vpn", "domain", "hosting", "maintenance fee", "internet fee", "phone fee",
    "electricity bill", "water bill", "gas bill", "tv bill",
    "waste management fee", "sanitation fee", "fire service tax", "municipal tax", "income tax", "corporate tax", "sales tax", "gst", "vat", "customs duty",
    "import duty", "export duty", "excise duty", "stamp duty", "registration fee", "notary fee", "legal fee", "court fee", "filing fee", "bar council fee",
    "patent fee", "trademark fee", "copyright fee", "royalty payment", "franchise fee", "brokerage fee", "transaction fee", "processing fee", "convenience fee", "late fee",
    "overdraft fee", "atm fee", "bank charge", "credit card bill", "debit card fee", "minimum balance fee", "interest payment", "emi payment", "mortgage", "car loan",
    "student loan", "housing loan", "business loan", "microfinance loan", "lease payment", "installment", "hire purchase fee", "pos machine rental", "terminal fee", "merchant fee",
    "annual fee", "renewal fee", "subscription renewal", "data pack", "sms pack", "roaming charges", "international call fee", "long distance fee", "line rental", "postpaid bill",
    "prepaid recharge", "dth recharge", "ott subscription", "music subscription", "gaming subscription", "online course fee", "exam fee", "certification fee", "training fee", "tuition fee",
    "canteen fee", "transport fee", "bus pass", "metro card", "toll tax", "road tax", "vehicle insurance", "health insurance", "life insurance", "travel insurance",
    "medical bill", "hospital bill", "doctor fee", "pharmacy bill", "lab test bill", "diagnostic fee", "surgery fee", "dental fee", "optician fee", "therapy fee"
]
,
  "Health": [
    "medicine", "doctor", "pharmacy", "consultation", "hospital", "checkup", "vaccine", "syringe",
    "bandage", "ointment", "thermometer", "stethoscope", "bp monitor", "glucose meter", "inhaler",
    "mask", "sanitizer", "soap", "vitamin", "supplement", "protein", "energy bar", "first aid kit",
    "surgery", "x-ray", "mri", "ultrasound", "scan", "blood test", "eye drops", "contact lens",
    "glasses", "hearing aid", "wheelchair", "crutches", "brace", "splint", "painkiller", "antibiotic",
    "antiseptic", "bandage roll", "therapeutic oil", "massage oil", "essential oil", "bath salts", "shampoo", "toothpaste", "mouthwash", "toothbrush",
    "dental floss", "handwash", "face wash", "skincare cream", "sunscreen", "lip balm", "moisturizer", "hair oil", "hair serum", "conditioner",
    "cotton swabs", "gauze", "plaster", "nasal spray", "cough syrup", "antacid", "digestive tablet", "oral rehydration salts", "rehydration drink", "tonic",
    "blood pressure tablet", "diabetes medicine", "cholesterol medicine", "thyroid medicine", "multivitamin", "calcium tablet", "iron supplement", "omega 3 capsule", "herbal supplement", "probiotic",
    "antihistamine", "allergy medicine", "sleeping pill", "sedative", "antidepressant", "antianxiety medicine", "pain relief gel", "cold pack", "hot pack", "heating pad",
    "nebulizer", "steam inhaler", "oxygen cylinder", "pulse oximeter", "defibrillator", "ventilator", "surgical gloves", "face shield", "ppe kit", "disinfectant spray",
    "wound dressing", "sutures", "surgical tape", "scalpel", "surgical scissors", "therapeutic band", "yoga mat", "fitness tracker", "heart rate monitor", "treadmill",
    "dumbbell", "kettlebell", "resistance band", "exercise bike", "elliptical", "rowing machine", "foam roller", "massager", "spa kit", "aromatherapy diffuser",
    "nutrition shake", "protein powder", "meal replacement", "energy drink", "herbal tea", "green tea", "weight loss supplement", "detox drink", "collagen supplement", "hair vitamin",
    "skin vitamin", "joint supplement", "prenatal vitamin", "baby formula", "infant drops", "diaper rash cream", "sanitary pad", "tampon", "menstrual cup", "menstrual disc"
]

  ,
  "Education": [
    "book", "notebook", "pen", "pencil", "eraser", "sharpener", "ruler", "calculator",
    "dictionary", "thesaurus", "textbook", "notepad", "marker", "highlighter", "glue",
    "scissors", "stapler", "paper", "binder", "folder", "whiteboard", "chalk", "projector",
    "laptop", "tablet", "backpack", "stationery kit", "sticky notes", "crayons", "colored pencils",
    "paint", "brush", "canvas", "journal", "planner", "calendar", "magazine", "library card",
    "exam paper", "certificate", "diploma", "tuition fee", "course", "workshop", "online class",
    "quiz", "assignment", "lecture notes", "research paper", "study guide",
    "school bag", "geometry box", "ink pen", "fountain pen", "ball pen", "gel pen", "chalkboard", "smartboard", "notice board", "map",
    "atlas", "globe", "flashcards", "worksheet", "lab manual", "experiment kit", "microscope", "test tube", "beaker", "bunsen burner",
    "protractor", "compass", "divider", "set square", "drawing sheet", "sketchbook", "drafting table", "art easel", "charcoal pencil", "oil pastels",
    "watercolors", "poster colors", "calligraphy pen", "ink bottle", "correction pen", "erasable pen", "paper clips", "binder clips", "rubber bands", "envelope",
    "index cards", "file folder", "document holder", "portfolio", "thesis", "dissertation", "syllabus", "curriculum", "lesson plan", "attendance register",
    "report card", "ID card", "badge", "degree", "scholarship form", "admission form", "prospectus", "reading light", "study lamp", "book stand",
    "exam pad", "clipboard", "chalk holder", "pen holder", "desk organizer", "classroom desk", "chair", "blackboard duster", "lab coat", "safety goggles",
    "student ID", "teacher ID", "marker refill", "smart pen", "e-book", "online quiz", "learning app", "MOOC course", "webinar", "seminar",
    "conference", "academic journal", "publication", "peer review", "footnote", "citation", "reference book", "encyclopedia", "workbook", "mock test"
  ],
  "Home": [
    "sofa", "table", "chair", "bed", "mattress", "pillow", "blanket", "curtain", "rug", "carpet",
    "lamp", "fan", "heater", "ac", "cabinet", "shelf", "mirror", "clock", "painting", "vase",
    "decor", "plant", "flower pot", "bookshelf", "wardrobe", "drawer", "desk", "stool", "bench", "shoe rack",
    "coat rack", "cushion", "bedding", "linen", "towel", "mat", "kitchenware", "cookware", "utensils", "plate",
    "cup", "glass", "bowl", "knife", "spoon", "fork", "tray", "basket",
    "side table", "coffee table", "dining table", "study table", "nightstand", "dresser", "ottoman", "recliner", "rocking chair", "bean bag",
    "floor lamp", "table lamp", "chandelier", "lantern", "candle holder", "candles", "photo frame", "wall art", "wall clock", "alarm clock",
    "curtain rod", "window blinds", "door mat", "bath mat", "shower curtain", "soap dispenser", "toothbrush holder", "toilet brush", "bucket", "mop",
    "broom", "dustpan", "vacuum cleaner", "air purifier", "humidifier", "dehumidifier", "water filter", "geyser", "microwave", "oven",
    "stove", "gas cylinder", "fridge", "freezer", "dishwasher", "washing machine", "dryer", "iron", "ironing board", "laundry basket",
    "storage box", "trunk", "locker", "safe", "toolbox", "tool kit", "ladder", "step stool", "shoe polish kit", "key holder",
    "umbrella stand", "door stopper", "doorknob", "doorbell", "security camera", "video door phone", "alarm system", "fire extinguisher", "smoke detector", "carbon monoxide detector",
    "outdoor furniture", "patio chair", "garden table", "swing", "hammock", "barbecue grill", "outdoor light", "watering can", "hose", "sprinkler",
    "compost bin", "recycling bin", "garbage bag", "dustbin", "storage jar", "spice rack", "cutting board", "measuring cup", "measuring spoon", "rolling pin"
  ],
  "Sports": [
    "football", "soccer", "basketball", "tennis", "badminton", "cricket", "hockey", "golf",
    "table tennis", "volleyball", "rugby", "swimming", "cycling", "running shoes", "helmet",
    "gloves", "bat", "ball", "net", "goal", "court", "stadium", "track", "bike", "skates",
    "skateboard", "paddle", "canoe", "kayak", "rowing", "gym equipment", "dumbbells", "barbell",
    "mat", "towel", "jersey", "shorts", "socks", "shoes", "whistle", "stopwatch", "water bottle",
    "goggles", "cap", "training kit", "sports bag", "fitness tracker", "heart rate monitor", "band",
    "goalkeeper gloves", "shin guard", "armband", "headband", "sweatband", "sports bra", "tracksuit", "hoodie", "sports cap", "sports jacket",
    "tennis racket", "badminton racket", "squash racket", "table tennis bat", "cricket pads", "cricket helmet", "wicket keeping gloves", "cricket stumps", "bails", "hockey stick",
    "golf club", "golf ball", "golf tee", "basketball hoop", "football goalpost", "volleyball net", "rugby ball", "swimming cap", "swimming fins", "snorkel",
    "diving mask", "surfboard", "windsurf board", "sailing boat", "rowing machine", "kayak paddle", "canoe paddle", "ski", "ski pole", "ski boots",
    "snowboard", "ice skates", "roller skates", "rollerblades", "sledge", "sled", "archery bow", "arrow", "quiver", "target board",
    "boxing gloves", "punching bag", "speed bag", "mma gloves", "headgear", "mouthguard", "jump rope", "exercise ball", "resistance band", "yoga block",
    "yoga strap", "pull-up bar", "dip bar", "power rack", "weight plates", "kettlebell", "medicine ball", "foam roller", "treadmill", "elliptical machine",
    "rowing ergometer", "spinning bike", "sports whistle", "referee card", "scoreboard", "cones", "hurdles", "javelin", "discus", "shot put"
  ],
"Pets": [
  "dog", "cat", "fish", "bird", "hamster", "rabbit", "turtle", "guinea pig", "parrot", "canary",
  "goldfish", "betta fish", "cockatiel", "lovebird", "ferret", "chinchilla", "gecko", "lizard", "snake", "frog",
  "cage", "leash", "collar", "harness", "tag", "id chip", "whistle", "tracker", "bell collar", "muzzle",
  "food", "dry food", "wet food", "treats", "biscuits", "bones", "fish flakes", "pellets", "seeds", "hay",
  "toys", "plush toy", "squeaky toy", "chew toy", "rope toy", "rubber ball", "ring toy", "frisbee", "laser pointer", "catnip toy",
  "bowl", "water bottle", "automatic feeder", "slow feeder", "fountain", "feeding mat", "treat dispenser", "snuffle mat", "food storage box", "litter scoop",
  "bed", "litter", "litter box", "training pad", "blanket", "pillow", "hammock", "nesting box", "sleeping bag", "straw bedding",
  "brush", "comb", "grooming glove", "shampoo", "conditioner", "detangler", "dryer", "scissors", "nail clipper", "toothbrush",
  "medicine", "vitamins", "supplements", "vaccination", "dewormer", "flea collar", "tick spray", "first aid kit", "ointment", "ear cleaner",
  "crate", "carrier", "playpen", "kennel", "aquarium", "terrarium", "vivarium", "aviary", "travel bag", "stroller",
  "scratch post", "cat tree", "perch", "swing", "ladder", "tunnel", "wheel", "exercise ball", "harness vest", "training clicker",
  "filter", "heater", "air pump", "net", "gravel", "substrate", "plants", "driftwood", "rock cave", "background poster",
  "perch stand", "cut­tlebone", "seed stick", "swing toy", "bell toy", "mirror toy", "nesting material", "egg incubator", "bird bath", "flight cage",
  "dog house", "cat house", "reptile hide", "heat lamp", "UVB light", "thermometer", "hygrometer", "water dish", "misting system", "feeder insects",
  "training whistle", "obedience book", "clicker trainer", "poop bag", "poop scoop", "litter deodorizer", "odor spray", "air purifier", "pet gate", "fence",
  "tracker collar", "GPS tag", "pet camera", "automatic door", "pet fountain", "smart feeder", "activity monitor", "treat launcher", "self-cleaning litter box", "robot toy"
]
  ,
  "Vehicles": [
    "car", "bike", "motorcycle", "scooter", "truck", "van", "bus", "bicycle", "e-bike", "tractor",
    "helmet", "gloves", "jacket", "boots", "knee guard", "elbow guard", "riding suit", "seat belt", "child seat", "airbag",
    "tire", "wheel", "spare tire", "alloy wheel", "rim", "tube", "valve", "lug nut", "hubcap", "axle",
    "engine", "battery", "brake", "disc brake", "drum brake", "brake pad", "oil", "coolant", "gear", "transmission",
    "clutch", "spark plug", "radiator", "fan belt", "air filter", "fuel filter", "cabin filter", "exhaust", "silencer", "turbocharger",
    "mirror", "rearview mirror", "side mirror", "indicator", "headlight", "tail light", "fog light", "led strip", "horn", "dashboard",
    "steering wheel", "handlebar", "pedal", "accelerator", "brake pedal", "clutch pedal", "gear lever", "handbrake", "kickstart", "ignition",
    "fuel", "fuel tank", "diesel", "petrol", "gas cylinder", "charging cable", "charging station", "EV battery", "hybrid motor", "inverter",
    "windshield", "rear glass", "window", "sunroof", "wiper", "washer fluid", "defogger", "roof rack", "luggage carrier", "tow bar",
    "seat", "seat cover", "carpet", "floor mat", "cushion", "armrest", "headrest", "cup holder", "glove box", "storage bin",
    "license plate", "number plate cover", "sticker", "decal", "paint", "wrap", "body kit", "spoiler", "bumper", "mudguard",
    "suspension", "shock absorber", "spring", "leaf spring", "strut", "tie rod", "ball joint", "control arm", "stabilizer", "differential",
    "gps", "camera", "dashcam", "parking sensor", "alarm", "remote key", "immobilizer", "tracker", "OBD device", "infotainment system",
    "music system", "speaker", "subwoofer", "amplifier", "bluetooth", "usb charger", "cigarette lighter", "lighter socket", "antenna", "navigation screen"
  ],

  "Office": [
    "chair", "desk", "computer", "laptop", "monitor", "printer", "scanner", "fax", "photocopier", "projector",
    "stapler", "staples", "notebook", "pen", "pencil", "eraser", "marker", "highlighter", "sharpener", "ruler",
    "folder", "binder", "file", "document", "badge", "storage box", "cabinet", "drawer", "locker", "shelf",
    "paper", "envelope", "letterhead", "sticky notes", "calendar", "planner", "whiteboard", "chalk", "board", "notice board",
    "lamp", "light", "tube light", "LED lamp", "desk lamp", "cable", "charger", "extension cord", "power strip", "UPS",
    "mouse", "keyboard", "headset", "speaker", "webcam", "microphone", "router", "modem", "switch", "ethernet cable",
    "screen", "projection screen", "laser pointer", "remote", "tripod", "stand", "bulletin board", "pin", "clip", "rubber band",
    "tape", "glue", "adhesive", "scissors", "cutter", "knife", "hole punch", "calculator", "diary", "journal",
    "scanner paper", "printer paper", "photo paper", "colored paper", "cardboard", "chart paper", "labels", "sticker", "ID card", "plastic cover",
    "software", "hard drive", "SSD", "USB drive", "memory card", "CD", "DVD", "external disk", "server", "cloud storage",
    "conference phone", "video conferencing system", "television", "digital board", "smart board", "tablet", "stylus", "graphics tablet", "VR headset", "presentation remote"
  ],

  "Beauty": [
    "lipstick", "lip balm", "foundation", "concealer", "powder", "compact", "blush", "bronzer", "eyeliner", "mascara",
    "nail polish", "nail remover", "perfume", "deodorant", "roll-on", "cream", "lotion", "moisturizer", "sunscreen", "face wash",
    "soap", "body wash", "toner", "serum", "eye cream", "makeup remover", "micellar water", "facial oil", "face gel", "hydrating mist",
    "hair oil", "hair mask", "shampoo", "conditioner", "dry shampoo", "hair spray", "mousse", "gel", "wax", "pomade",
    "hair dryer", "straightener", "curler", "hot brush", "roller", "wig", "hair extension", "clip-in extension", "hairband", "scrunchie",
    "brush", "comb", "mirror", "compact mirror", "magnifying mirror", "tweezers", "nail file", "nail buffer", "cuticle cutter", "nail scissors",
    "pumice", "foot file", "pedicure kit", "manicure kit", "exfoliator", "scrub", "bath sponge", "loofah", "body scrub", "face scrub",
    "hand cream", "foot cream", "shaving cream", "razor", "aftershave", "trimmer", "epilator", "wax strips", "wax heater", "thread",
    "mask", "sheet mask", "clay mask", "peel mask", "eye patch", "lip mask", "sleeping mask", "charcoal mask", "gold mask", "hydrogel mask",
    "cotton pad", "cotton ball", "swab", "makeup sponge", "beauty blender", "brush set", "powder puff", "applicator", "palette", "case",
    "spray", "setting spray", "hair spray", "fragrance mist", "de-tangler", "serum spray", "sunblock spray", "dry oil", "rose water", "tonic"
  ],
  "Toys": [
    "lego", "doll", "action figure", "car toy", "truck toy", "bike toy", "scooter toy", "train set", "train track", "track set",
    "puzzle", "jigsaw puzzle", "board game", "card game", "chess", "ludo", "snakes and ladders", "scrabble", "monopoly", "uno",
    "ball", "football toy", "basketball toy", "cricket set", "badminton set", "soft toy", "stuffed animal", "teddy bear", "plushie", "puppet",
    "blocks", "building set", "construction set", "play-doh", "clay", "craft kit", "painting kit", "drawing kit", "sticker book", "coloring book",
    "crayons", "colored pencils", "markers", "chalk", "slime", "putty", "squishy", "fidget spinner", "stress ball", "magic cube",
    "toy gun", "nerf gun", "water gun", "spinning top", "yo-yo", "kite", "frisbee", "balloon", "marbles", "ring toss",
    "rocket", "spaceship", "figurine", "superhero figure", "barbie", "baby doll", "robot toy", "remote car", "remote truck", "remote boat",
    "helicopter toy", "drone toy", "airplane toy", "ride-on", "balance bike", "tricycle", "scooter toy", "rocking horse", "play tent", "playhouse",
    "kitchen set", "doctor set", "tool set", "cash register", "shopping cart toy", "grocery set", "tea set", "cooking set", "cleaning set", "mini appliances",
    "game console", "video game toy", "tablet toy", "phone toy", "musical instrument toy", "xylophone", "keyboard toy", "piano toy", "drum toy", "guitar toy",
    "microphone toy", "karaoke toy", "dance mat", "educational toy", "flash cards", "alphabet blocks", "number blocks", "shape sorter", "stacking rings", "abacus",
    "science kit", "robotics kit", "coding toy", "experiment set", "magnifying glass", "binocular toy", "globe toy", "map puzzle", "space kit", "dinosaur set",
    "farm set", "zoo animals", "wildlife set", "horse stable", "pet toy set", "aquarium toy", "pirate ship", "castle set", "knight toy", "soldier toy"
  ],
  "Drinks": [
    "water", "sparkling water", "mineral water", "juice", "orange juice", "apple juice", "grape juice", "cranberry juice", "pineapple juice", "tomato juice",
    "carrot juice", "beetroot juice", "watermelon juice", "pomegranate juice", "lemonade", "lime soda", "ginger ale", "cola", "soda", "tonic water",
    "coffee", "black coffee", "latte", "espresso", "americano", "cappuccino", "frappuccino", "mocha", "macchiato", "cold brew",
    "tea", "black tea", "green tea", "white tea", "oolong tea", "herbal tea", "chai", "masala chai", "chai latte", "iced tea",
    "milk", "soy milk", "almond milk", "coconut milk", "oat milk", "milkshake", "banana milkshake", "chocolate milkshake", "strawberry milkshake", "vanilla milkshake",
    "smoothie", "fruit smoothie", "protein shake", "energy drink", "sports drink", "kombucha", "mocktail", "cocktail", "mojito", "martini",
    "margarita", "pina colada", "daiquiri", "whiskey", "vodka", "rum", "gin", "tequila", "brandy", "cognac",
    "beer", "lager", "ale", "stout", "cider", "wine", "red wine", "white wine", "rose wine", "champagne",
    "hot chocolate", "cocoa", "chai latte", "matcha", "turmeric latte", "ginger tea", "detox drink", "buttermilk", "lassi", "falooda"
  ],
  "Shopping": [
    "myntra", "flipkart", "amazon", "snapdeal", "ajio", "shopclues", "ebay", "tatacliq", "paytm mall", "shopee",
    "mall", "store", "retail", "market", "supermarket", "grocery store", "department store", "outlet", "boutique", "thrift store",
    "cart", "basket", "shopping bag", "trolley", "checkout", "payment", "cashback", "voucher", "coupon", "discount",
    "offer", "deal", "clearance sale", "flash sale", "big billion sale", "festival sale", "exchange offer", "buy one get one", "gift card", "loyalty points",
    "wishlist", "favorites", "saved items", "fashion", "clothing", "menswear", "womenswear", "kidswear", "footwear", "accessories",
    "electronics", "mobile", "smartphone", "tablet", "laptop", "desktop", "appliance", "TV", "washing machine", "fridge",
    "furniture", "sofa", "table", "chair", "bed", "wardrobe", "home decor", "curtain", "rug", "lamp",
    "books", "novel", "magazine", "stationery", "notebook", "pen", "toys", "board game", "puzzle", "sports gear",
    "cosmetics", "makeup", "skincare", "haircare", "fragrance", "jewelry", "necklace", "ring", "bracelet", "watch",
    "bags", "handbag", "backpack", "wallet", "belt", "sunglasses", "gadgets", "headphones", "speaker", "smartwatch"
  ],
    "PersonalCareHygiene": [
    "toothbrush", "toothpaste", "floss", "mouthwash", "soap", "body wash", "face wash", "cleanser", "toner", "moisturizer",
    "deodorant", "roll-on", "perfume", "shampoo", "conditioner", "hair oil", "hair gel", "hair spray", "serum", "razor",
    "shaving cream", "aftershave", "trimmer", "wax", "cotton pads", "cotton balls", "tissue", "wet wipes", "hand sanitizer", "handwash",
    "nail cutter", "nail file", "cuticle oil", "nail polish remover", "foot cream", "hand cream", "lip balm", "sunscreen", "body lotion", "talcum powder",
    "face mask", "sheet mask", "scrub", "exfoliator", "bath sponge", "pumice stone", "shower gel", "bath salts", "body butter", "body mist",
    "comb", "brush", "hair band", "hair clips", "sanitary pads", "tampons", "menstrual cup", "diaper", "baby wipes", "baby powder",
    "baby lotion", "baby shampoo", "baby soap", "diaper rash cream", "antiseptic", "ointment", "pain relief spray", "balm", "eye drops", "ear buds",
    "cotton swabs", "tweezers", "mirror", "grooming kit", "grooming scissors", "beard oil", "beard wax", "beard balm", "massage oil", "therapeutic oil",
    "ayurvedic oil", "herbal powder", "organic soap", "face roller", "jade roller", "gua sha", "foot scrub", "foot spa", "electric toothbrush", "travel kit"
  ],
  "EventsGifts": [
    "birthday gift", "birthday card", "gift box", "wrapping paper", "ribbon", "balloon", "cake", "candles", "party hat", "streamers",
    "party supplies", "confetti", "banner", "party favor", "anniversary gift", "wedding gift", "flowers", "bouquet", "chocolates", "greeting card",
    "teddy bear", "photo frame", "jewelry", "necklace", "bracelet", "ring", "watch", "perfume", "home decor", "vase",
    "ornament", "plant", "succulent", "cake topper", "gift bag", "gift wrap", "handmade gift", "scrapbook", "diary", "planner",
    "candle", "scented candle", "soap gift set", "bath gift set", "tea gift set", "coffee gift set", "wine bottle", "champagne", "liquor", "gourmet basket",
    "cookie jar", "cookie tin", "chocolate box", "fruit basket", "artisan gift", "craft kit", "doll", "toy car", "lego set", "board game",
    "puzzle", "photo album", "engraved gift", "personalized gift", "keychain", "wallet", "handbag", "scarves", "hat", "gloves",
    "stationery", "pen set", "marker set", "highlighter set", "notebook", "diary", "certificate frame", "trophy", "medal", "award",
    "plush toy", "figurine", "art kit", "painting kit", "crochet kit", "knitting kit", "cookbook", "recipe book", "music CD", "movie DVD"
  ],
  "CharityDonations": [
    "donation", "charity", "offering", "temple donation", "church donation", "mosque donation", "NGO", "crowdfunding", "social cause", "fundraiser",
    "charity event", "blood donation", "food donation", "clothes donation", "toy donation", "volunteering", "helping hand", "sponsorship", "grant", "relief fund",
    "disaster relief", "medical aid", "educational aid", "child support", "elderly support", "animal welfare", "pet adoption", "rescue center", "community service", "social work",
    "fund collection", "donation box", "fund drive", "charity auction", "donor", "beneficiary", "funding", "alms", "endowment", "nonprofit",
    "foundation", "philanthropy", "charitable trust", "social project", "volunteer program", "mission", "aid project", "support group", "fundraising gala", "charity campaign",
    "eco donation", "tree plantation", "green project", "water project", "hygiene project", "orphanage support", "school support", "hospital support", "animal shelter", "rehabilitation",
    "fund distribution", "community upliftment", "microfinance", "donor card", "membership donation", "regular donation", "emergency aid", "disaster relief fund", "charity drive", "donation campaign",
    "clothes drive", "food drive", "book drive", "medical camp", "blood camp", "charity marathon", "charity walk", "volunteer drive", "social awareness", "donor recognition"
  ],
  "SavingsInvestments": [
    "savings account", "fixed deposit", "FD", "recurring deposit", "RD", "SIP", "mutual fund", "stocks", "bonds", "crypto",
    "bitcoin", "ethereum", "gold", "silver", "real estate", "pension", "retirement fund", "insurance", "life insurance", "health insurance",
    "ULIP", "annuities", "government bonds", "treasury bills", "ETF", "index fund", "portfolio", "dividend", "interest", "capital gains",
    "stock market", "share trading", "brokerage", "demat account", "digital gold", "commodity", "futures", "options", "cryptocurrency", "token",
    "NFT", "financial plan", "budget", "emergency fund", "sinking fund", "college fund", "children's fund", "retirement savings", "pension plan", "superannuation",
    "investment plan", "wealth management", "asset allocation", "capital", "equity", "debt", "mutual fund scheme", "gold ETF", "government security", "corporate bond",
    "bank deposit", "interest income", "dividend payout", "capital appreciation", "risk management", "financial advisory", "fund manager", "portfolio diversification", "rebalancing", "inflation hedge",
    "tax saving", "tax benefit", "section 80C", "section 80D", "long-term investment", "short-term investment", "liquid fund", "debt fund", "equity fund", "hybrid fund",
    "retirement corpus", "financial goal", "asset growth", "wealth creation", "compound interest", "safety net", "financial security", "liquidity", "capital protection", "financial literacy"
  ],
  "RepairsMaintenance": [
    "plumber", "electrician", "carpenter", "mechanic", "renovation", "paint", "repair", "service", "spare parts", "tool kit",
    "wrench", "screwdriver", "hammer", "nails", "screws", "drill", "saw", "adhesive", "sealant", "pipe",
    "valve", "tap", "faucet", "heater repair", "AC repair", "fan repair", "TV repair", "fridge repair", "washing machine repair", "microwave repair",
    "oven repair", "stove repair", "chimney repair", "geyser repair", "door repair", "window repair", "lock repair", "alarm repair", "cable repair", "network repair",
    "battery replacement", "oil change", "engine repair", "gear repair", "tyre replacement", "brake service", "wheel alignment", "suspension repair", "radiator repair", "filter replacement",
    "maintenance kit", "cleaning service", "pest control", "roof repair", "floor repair", "plumbing parts", "electrical parts", "hardware", "software update", "appliance service",
    "car service", "bike service", "home service", "interior repair", "exterior repair", "painting kit", "brush set", "roller", "sandpaper", "glue gun",
    "adhesive tape", "drain cleaning", "pipe fitting", "socket repair", "circuit repair", "fuse replacement", "wiring", "insulation", "switch repair", "fan blade",
    "motor repair", "compressor repair", "pump repair", "valve repair", "chimney cleaning", "gutter repair", "door hinge", "window hinge", "key replacement", "service charge"
  ],
  "TransportationFuel": [
    "petrol", "diesel", "CNG", "LPG", "fuel", "gasoline", "electric charging", "toll", "toll plaza", "parking",
    "metro card", "bus pass", "train pass", "rail ticket", "flight ticket", "airline charge", "cab", "taxi", "uber", "ola",
    "auto-rickshaw", "bike rental", "car rental", "van rental", "scooter rental", "fuel station", "service station", "vehicle maintenance", "vehicle repair", "tyre change",
    "oil change", "battery replacement", "gear oil", "brake oil", "coolant", "windshield washer", "parking fee", "garage fee", "roadside assistance", "road tax",
    "vehicle insurance", "vehicle registration", "emission test", "inspection", "speed toll", "highway toll", "bridge toll", "ferry fee", "driver allowance", "driver tip",
    "car wash", "cleaning service", "lubricant", "spark plug", "air filter", "fuel filter", "engine oil", "chain oil", "lubrication", "brake pad",
    "helmet", "gloves", "jack", "tool kit", "spare tyre", "wheel alignment", "wheel balancing", "vehicle accessories", "roof rack", "sunglasses",
    "navigation", "GPS", "dashboard camera", "trip meter", "odometer", "speed limit fine", "parking sensor", "reflector", "indicator bulb", "headlight"
  ],
  "TechnologySubscriptions": [
    "Netflix", "Prime", "Hotstar", "Disney+", "Hulu", "Spotify", "YouTube Premium", "Apple Music", "Google One", "iCloud",
    "Google Drive", "Dropbox", "Microsoft 365", "Adobe Creative Cloud", "Canva Pro", "VPN subscription", "antivirus", "software license", "app purchase", "app subscription",
    "game subscription", "PlayStation Plus", "Xbox Game Pass", "Steam", "Epic Games", "mobile data plan", "internet plan", "cloud storage", "domain", "web hosting",
    "SEO tools", "graphic tools", "video editor", "photo editor", "productivity apps", "task manager", "calendar app", "note app", "email service", "premium newsletter",
    "online course", "course subscription", "educational app", "learning platform", "eBook subscription", "magazine subscription", "news subscription", "stock market app", "trading app", "crypto exchange",
    "investment app", "banking app", "digital wallet", "payment app", "tax software", "budget app", "expense tracker", "health app", "fitness app", "meditation app",
    "music app", "video streaming", "TV streaming", "movie subscription", "sports app", "live sports", "gaming app", "game pass", "cloud gaming", "VPN service",
    "security software", "antimalware", "firewall", "password manager", "two-factor authentication", "data backup", "cloud backup", "online storage", "photo storage", "document storage"
  ],
  "Other": []
}
export const companyCategories = [{name:"Flipkart",amount:0},{"name":"Ola",amount:0},{"name":"Zomato",amount:0}];
export const monthslist = [
  { name: "January", amount: 0 },
  { name: "February", amount: 0 },
  { name: "March", amount: 0 },
  { name: "April", amount: 0 },
  { name: "May", amount: 0 },
  { name: "June", amount: 0 },
  { name: "July", amount: 0 },
  { name: "August", amount: 0 },
  { name: "September", amount: 0 },
  { name: "October", amount: 0 },
  { name: "November", amount: 0 },
  { name: "December", amount: 0 },
];
